import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useParams, useNavigate, useSearchParams, Link } from 'react-router-dom';
import { useBookStore } from '../stores/bookStore';
import { useReadingProgressStore } from '../stores/readingProgressStore';
import { useBookmarkStore } from '../stores/bookmarkStore';
import { useAnnotationStore } from '../stores/annotationStore';
import { useToastStore } from '../stores/toastStore';
import { useReadingSessionStore } from '../stores/readingSessionStore';
import { getBookSignedUrl } from '../services/bookService';
import { ReaderToolbar } from '../components/reader/ReaderToolbar';
import { ReaderSidebar } from '../components/reader/ReaderSidebar';
import { ReaderViewport } from '../components/reader/ReaderViewport';
import { ReadingProgressBar } from '../components/reader/ReadingProgressBar';
import { MemoryBridgeCard } from '../components/reader/MemoryBridgeCard';
import { useSwipeGesture } from '../hooks/useSwipeGesture';
import { ConcentricPortal } from '../components/ConcentricPortal';
import { KIN_ARCHIVE_BY_ID } from '../data/kinArchive';
import { ReadingSession } from '../types/book';

export const ReaderScreen: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const { getBookById, updateBook, fetchBooks } = useBookStore();
  const { getProgress, fetchProgress, saveProgress } = useReadingProgressStore();
  const { getBookmarks, fetchBookmarks, addBookmark, removeBookmark, isPageBookmarked } = useBookmarkStore();
  const {
    fetchAnnotations,
    getAnnotationsForPage,
    addAnnotation,
    updateAnnotation,
    deleteAnnotation,
    annotations,
  } = useAnnotationStore();
  const { showToast } = useToastStore();

  const {
    sessionsByBookId,
    isGeneratingRecap,
    generatingSessionId,
    fetchSessions,
    startSession,
    recordPageActivity,
    recordUserInteraction,
    incrementActiveDwellTime,
    finalizeActiveSession,
    updateSessionBoundaries,
    generateRecapForSession,
    markRecapViewed,
    deleteSession,
  } = useReadingSessionStore();

  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [totalPages, setTotalPages] = useState<number>(1);
  const [zoomScale, setZoomScale] = useState<number>(1.0);
  const [isFocusMode, setIsFocusMode] = useState<boolean>(false);
  const [isAddingNote, setIsAddingNote] = useState<boolean>(false);
  const [activeSidebar, setActiveSidebar] = useState<'thumbnails' | 'bookmarks' | 'notes' | 'archive' | 'recap' | null>(null);
  const [loadingUrl, setLoadingUrl] = useState<boolean>(true);
  const [isQuietReading, setIsQuietReading] = useState<boolean>(false);
  const [isChromeFaded, setIsChromeFaded] = useState<boolean>(false);

  const checkIsMobile = () =>
    typeof window !== 'undefined' && (window.innerWidth <= 768 || window.innerHeight <= 500);
  const [isMobile, setIsMobile] = useState<boolean>(checkIsMobile);

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(checkIsMobile());
    };
    window.addEventListener('resize', handleResize);
    window.addEventListener('orientationchange', handleResize);
    return () => {
      window.removeEventListener('resize', handleResize);
      window.removeEventListener('orientationchange', handleResize);
    };
  }, []);

  // Memory Bridge states
  const [showingMemoryBridge, setShowingMemoryBridge] = useState<boolean>(false);
  const [activeMemoryBridgeSessionId, setActiveMemoryBridgeSessionId] = useState<string | null>(null);

  const book = id ? getBookById(id) : undefined;
  const progress = id ? getProgress(id) : undefined;
  const bookmarks = id ? getBookmarks(id) : [];
  const bookAnnotations = id ? annotations.filter((a) => a.book_id === id) : [];
  const pageAnnotations = id ? getAnnotationsForPage(id, currentPage) : [];
  const bookSessions = id ? sessionsByBookId[id] || [] : [];
  const unviewedMeaningfulSession = bookSessions.find((s) => s.is_meaningful && !s.recap_viewed_at);

  // Derive active session directly from store to prevent stale closure / state de-sync
  const activeMemoryBridgeSession = activeMemoryBridgeSessionId
    ? bookSessions.find((s) => s.id === activeMemoryBridgeSessionId) || null
    : null;

  // Track which sessions had an automatic recap generation attempt to avoid infinite retries
  const autoGeneratedSessionRef = useRef<Record<string, boolean>>({});

  // 1. Initial data fetch & Memory Bridge discovery
  useEffect(() => {
    fetchBooks();
    if (id) {
      fetchProgress(id);
      fetchBookmarks(id);
      fetchAnnotations(id);
      fetchSessions(id).then((sessions) => {
        // Find latest meaningful session that hasn't been viewed yet
        const sorted = sessions.slice().sort(
          (a, b) => new Date(b.ended_at).getTime() - new Date(a.ended_at).getTime()
        );
        const latestUnviewed = sorted.find((s) => s.is_meaningful && !s.recap_viewed_at);
        if (latestUnviewed) {
          const endedAgoMs = Date.now() - new Date(latestUnviewed.ended_at).getTime();
          // Display recap if session was not just closed this very second (> 20s ago)
          if (endedAgoMs > 20000) {
            setActiveMemoryBridgeSessionId(latestUnviewed.id);
            setShowingMemoryBridge(true);
          }
        }
      });
    }
  }, [id, fetchBooks, fetchProgress, fetchBookmarks, fetchAnnotations, fetchSessions]);

  // 2. Fetch signed URL or local URL for book's file
  useEffect(() => {
    let active = true;
    const loadUrl = async () => {
      if (!book) return;
      setLoadingUrl(true);

      // If file_path is already a direct path/URL
      if (
        book.file_path.startsWith('blob:') ||
        book.file_path.startsWith('data:') ||
        book.file_path.startsWith('http') ||
        book.file_path.startsWith('/')
      ) {
        if (active) {
          setPdfUrl(book.file_path);
          setLoadingUrl(false);
        }
        return;
      }

      const signed = await getBookSignedUrl(book.file_path);
      if (active) {
        setPdfUrl(signed || book.file_path);
        setLoadingUrl(false);
      }
    };

    loadUrl();
    return () => {
      active = false;
    };
  }, [book]);

  // 3. Set initial page from URL query param or saved progress
  useEffect(() => {
    const pageParam = searchParams.get('page');
    if (pageParam) {
      const p = parseInt(pageParam, 10);
      if (!isNaN(p) && p >= 1) {
        setCurrentPage(p);
        return;
      }
    }

    if (progress?.current_page) {
      setCurrentPage(progress.current_page);
    }
    if (progress?.zoom_level) {
      setZoomScale(progress.zoom_level);
    }
    if (progress?.total_pages) {
      setTotalPages(progress.total_pages);
    } else if (book?.page_count) {
      setTotalPages(book.page_count);
    }
  }, [searchParams, progress, book]);

  // 4. Change page handler with auto-save & session tracking
  const handlePageChange = useCallback(
    (targetPage: number) => {
      const clamped = Math.max(1, Math.min(totalPages || 1, targetPage));
      setCurrentPage(clamped);

      // If user turns page while Memory Bridge card is displayed, dismiss and mark viewed
      if (showingMemoryBridge && activeMemoryBridgeSessionId) {
        markRecapViewed(activeMemoryBridgeSessionId);
        setShowingMemoryBridge(false);
      }

      if (id) {
        saveProgress(id, clamped, totalPages, 0, zoomScale);
        recordPageActivity(clamped, book?.file_path, book?.title, book?.author);
      }
    },
    [id, totalPages, zoomScale, saveProgress, recordPageActivity, book, showingMemoryBridge, activeMemoryBridgeSessionId, markRecapViewed]
  );

  // 4b. Start active session tracking when reader opens
  useEffect(() => {
    if (id && currentPage >= 1) {
      startSession(id, currentPage);
    }
  }, [id, currentPage, startSession]);

  // 4c. Track active user interactions and dwell time
  useEffect(() => {
    const handleActivity = () => {
      recordUserInteraction();
    };

    const events = ['mousemove', 'mousedown', 'scroll', 'touchstart', 'keydown'];
    events.forEach((evt) => window.addEventListener(evt, handleActivity, { passive: true }));

    // Increment active reading dwell time every second when visible
    const timer = setInterval(() => {
      if (typeof document !== 'undefined' && document.visibilityState === 'visible') {
        incrementActiveDwellTime(1);
      }
    }, 1000);

    return () => {
      events.forEach((evt) => window.removeEventListener(evt, handleActivity));
      clearInterval(timer);
    };
  }, [recordUserInteraction, incrementActiveDwellTime]);

  // 4d. Finalize active session on unmount, tab hide, or beforeunload
  const bookRef = useRef(book);
  bookRef.current = book;

  useEffect(() => {
    const flushSession = () => {
      const currentBook = bookRef.current;
      if (currentBook) {
        finalizeActiveSession(currentBook.file_path, currentBook.title, currentBook.author);
      } else {
        finalizeActiveSession();
      }
    };

    const handleVisibilityChange = () => {
      if (document.visibilityState === 'hidden') {
        flushSession();
      } else if (document.visibilityState === 'visible') {
        // Tab restored: ensure reading session continues smoothly
        if (id && currentPage >= 1) {
          startSession(id, currentPage);
        }
      }
    };

    const handleBeforeUnload = () => {
      flushSession();
    };

    document.addEventListener('visibilitychange', handleVisibilityChange);
    window.addEventListener('beforeunload', handleBeforeUnload);

    return () => {
      document.removeEventListener('visibilitychange', handleVisibilityChange);
      window.removeEventListener('beforeunload', handleBeforeUnload);
      flushSession();
    };
  }, [id, currentPage, finalizeActiveSession, startSession]);

  // 4e. Generate recap if active memory bridge is pending recap and book is loaded
  useEffect(() => {
    if (
      showingMemoryBridge &&
      activeMemoryBridgeSession &&
      !activeMemoryBridgeSession.recap &&
      !activeMemoryBridgeSession.recap_error &&
      !isGeneratingRecap &&
      !autoGeneratedSessionRef.current[activeMemoryBridgeSession.id] &&
      book
    ) {
      autoGeneratedSessionRef.current[activeMemoryBridgeSession.id] = true;
      generateRecapForSession(
        activeMemoryBridgeSession.id,
        book.file_path,
        book.title,
        book.author
      );
    }
  }, [showingMemoryBridge, activeMemoryBridgeSession, isGeneratingRecap, book, generateRecapForSession]);

  // 4f. Memory bridge action handlers
  const handleContinueReading = useCallback(() => {
    if (activeMemoryBridgeSession) {
      markRecapViewed(activeMemoryBridgeSession.id);
      // Navigate to end_page (continuation position) if reader is currently before it
      if (currentPage < activeMemoryBridgeSession.end_page) {
        handlePageChange(activeMemoryBridgeSession.end_page);
      }
    }
    setShowingMemoryBridge(false);
  }, [activeMemoryBridgeSession, currentPage, handlePageChange, markRecapViewed]);

  const handleDismissMemoryBridge = useCallback(() => {
    if (activeMemoryBridgeSession) {
      markRecapViewed(activeMemoryBridgeSession.id);
    }
    setShowingMemoryBridge(false);
  }, [activeMemoryBridgeSession, markRecapViewed]);

  const handleUpdateBoundaries = useCallback(
    async (startPage: number, endPage: number) => {
      if (!activeMemoryBridgeSession || !book) return;
      // Allow regeneration attempt on boundary change
      if (autoGeneratedSessionRef.current[activeMemoryBridgeSession.id]) {
        delete autoGeneratedSessionRef.current[activeMemoryBridgeSession.id];
      }
      const updated = await updateSessionBoundaries(
        activeMemoryBridgeSession.id,
        startPage,
        endPage,
        book.file_path,
        book.title,
        book.author
      );
      if (updated) {
        showToast({
          type: 'success',
          message: `Reading boundaries updated to Pages ${startPage}–${endPage}. Regenerating recap…`,
        });
      }
    },
    [activeMemoryBridgeSession, book, updateSessionBoundaries, showToast]
  );

  const handleRegenerateRecap = useCallback(async () => {
    if (!activeMemoryBridgeSession || !book) return;
    showToast({ type: 'info', message: 'Generating reading session recap…' });
    const ok = await generateRecapForSession(
      activeMemoryBridgeSession.id,
      book.file_path,
      book.title,
      book.author
    );
    if (ok) {
      showToast({ type: 'success', message: 'Reading recap generated!' });
    } else {
      const sess = bookSessions.find((s) => s.id === activeMemoryBridgeSession.id);
      showToast({
        type: 'error',
        message: sess?.recap_error || 'Could not generate recap with Gemini. Check API key or network connection.',
      });
    }
  }, [activeMemoryBridgeSession, book, bookSessions, generateRecapForSession, showToast]);

  // 5. Document load success
  const handleDocumentLoadSuccess = (numPages: number) => {
    setTotalPages(numPages);
    if (id && (!book?.page_count || book.page_count !== numPages)) {
      updateBook(id, { page_count: numPages });
    }
  };

  // 6. Bookmark toggle
  const handleToggleBookmark = async () => {
    if (!id) return;
    const isBookmarked = isPageBookmarked(id, currentPage);
    if (isBookmarked) {
      const bm = bookmarks.find((b) => b.book_id === id && b.page_number === currentPage);
      if (bm) {
        await removeBookmark(bm.id);
        showToast({ type: 'info', message: `Bookmark on page ${currentPage} removed` });
      }
    } else {
      await addBookmark(id, currentPage, `Page ${currentPage} study note`);
      showToast({ type: 'success', message: `Page ${currentPage} bookmarked` });
    }
  };

  // 7. Add annotation at coordinates
  const handleAddNoteAt = async (x_percent: number, y_percent: number) => {
    if (!id) return;
    setIsAddingNote(false);
    const newAnn = await addAnnotation({
      book_id: id,
      page_number: currentPage,
      type: 'note',
      content: 'Observation on page ' + currentPage,
      x_percent,
      y_percent,
    });
    if (newAnn) {
      showToast({ type: 'success', message: `Note placed on page ${currentPage}` });
    }
  };

  // 8. Pin Kin Archive asset to current page
  const handlePinArchiveAsset = async (assetId: string) => {
    if (!id) return;
    const asset = KIN_ARCHIVE_BY_ID[assetId];
    const newAnn = await addAnnotation({
      book_id: id,
      page_number: currentPage,
      type: 'archive_ref',
      content: asset?.title || 'Studio reference',
      ref_archive_asset_id: assetId,
      x_percent: 50,
      y_percent: 35,
    });
    if (newAnn) {
      showToast({ type: 'success', message: `Pinned ${asset?.code} to page ${currentPage}` });
    }
  };

  // 8. Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't intercept if user is typing in an input
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
        return;
      }

      switch (e.key) {
        case 'ArrowLeft':
        case 'PageUp':
          e.preventDefault();
          handlePageChange(currentPage - 1);
          break;
        case 'ArrowRight':
        case 'PageDown':
          e.preventDefault();
          handlePageChange(currentPage + 1);
          break;
        case '+':
        case '=':
          e.preventDefault();
          setZoomScale((z) => Math.min(2.5, z + 0.15));
          break;
        case '-':
        case '_':
          e.preventDefault();
          setZoomScale((z) => Math.max(0.5, z - 0.15));
          break;
        case '0':
          e.preventDefault();
          setZoomScale(1.0);
          break;
        case 'b':
        case 'B':
          e.preventDefault();
          handleToggleBookmark();
          break;
        case 'f':
        case 'F':
          e.preventDefault();
          setIsFocusMode((f) => !f);
          break;
        case 'q':
        case 'Q':
          e.preventDefault();
          setIsQuietReading((q) => !q);
          break;
        case 'Escape':
          if (isAddingNote) {
            e.preventDefault();
            setIsAddingNote(false);
          } else if (isFocusMode) {
            e.preventDefault();
            setIsFocusMode(false);
          } else if (activeSidebar) {
            e.preventDefault();
            setActiveSidebar(null);
          }
          break;
        default:
          break;
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [currentPage, handlePageChange, isFocusMode, isAddingNote, activeSidebar, handleToggleBookmark]);

  // Chrome fade-on-read inactivity timer (3.5s)
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout> | null = null;

    const resetTimer = () => {
      setIsChromeFaded(false);
      if (timer) clearTimeout(timer);
      timer = setTimeout(() => {
        setIsChromeFaded(true);
      }, 3500);
    };

    resetTimer();

    const events = ['mousemove', 'mousedown', 'scroll', 'touchstart', 'keydown'];
    events.forEach((evt) => window.addEventListener(evt, resetTimer, { passive: true }));

    return () => {
      if (timer) clearTimeout(timer);
      events.forEach((evt) => window.removeEventListener(evt, resetTimer));
    };
  }, []);

  if (!book && !loadingUrl) {
    return (
      <div style={{ padding: '60px 24px', textAlign: 'center' }}>
        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--color-primary)' }}>Book not found</h2>
        <p style={{ color: 'var(--color-text-secondary)', marginBottom: '20px' }}>
          This document could not be found in your private library.
        </p>
        <Link to="/library" className="btn-primary" style={{ padding: '10px 20px', borderRadius: 'var(--radius-pill)', textDecoration: 'none' }}>
          Return to Library
        </Link>
      </div>
    );
  }

  const swipeHandlers = useSwipeGesture({
    onSwipeLeft: () => {
      if (zoomScale <= 1.0) {
        handlePageChange(currentPage + 1);
      }
    },
    onSwipeRight: () => {
      if (zoomScale <= 1.0) {
        handlePageChange(currentPage - 1);
      }
    },
  });

  const bookmarked = id ? isPageBookmarked(id, currentPage) : false;

  return (
    <div
      className={isQuietReading ? 'quiet-reading-active' : ''}
      style={{
        display: 'flex',
        flexDirection: 'column',
        position: isFocusMode ? 'fixed' : 'relative',
        inset: isFocusMode ? 0 : 'auto',
        height: isFocusMode ? '100vh' : 'calc(100vh - 64px)',
        zIndex: isFocusMode ? 9999 : 'auto',
        backgroundColor: 'var(--color-background)',
        overflow: 'hidden',
      }}
    >
      <ReadingProgressBar currentPage={currentPage} totalPages={totalPages} />

      {/* Top Toolbar in Kin Layer */}
      <div className={`reader-kin-chrome ${isChromeFaded ? 'reader-kin-chrome-faded' : ''}`}>
        <ReaderToolbar
          bookTitle={book?.title || 'PDF Document'}
          bookId={book?.id || ''}
          currentPage={currentPage}
          totalPages={totalPages}
          zoomScale={zoomScale}
          isBookmarked={bookmarked}
          isFocusMode={isFocusMode}
          isAddingNote={isAddingNote}
          hasUnreadRecap={Boolean(unviewedMeaningfulSession)}
          activeSidebar={activeSidebar}
          onPageChange={handlePageChange}
          onZoomChange={setZoomScale}
          onToggleBookmark={handleToggleBookmark}
          onToggleAddNote={() => setIsAddingNote(!isAddingNote)}
          onToggleFocusMode={() => setIsFocusMode(!isFocusMode)}
          onToggleSidebar={(sidebar) =>
            setActiveSidebar((current) => (current === sidebar ? null : sidebar))
          }
          onFitWidth={() => setZoomScale(1.3)}
          onFitPage={() => setZoomScale(1.0)}
          isQuietReading={isQuietReading}
          onToggleQuietReading={() => setIsQuietReading((q) => !q)}
        />
      </div>

      {/* Reader Main Layout */}
      <div {...swipeHandlers} style={{ display: 'flex', flex: 1, overflow: 'hidden', position: 'relative' }}>
        {/* Floating Memory Bridge (Previously...) Card */}
        {showingMemoryBridge && activeMemoryBridgeSession && (
          <div
            style={{
              position: 'absolute',
              top: '16px',
              left: '16px',
              right: activeSidebar && !isMobile ? '336px' : '16px',
              zIndex: 30,
              display: 'flex',
              justifyContent: 'center',
              pointerEvents: 'none',
            }}
          >
            <div style={{ pointerEvents: 'auto', width: '100%', maxWidth: '720px' }}>
              <MemoryBridgeCard
                session={activeMemoryBridgeSession}
                bookTitle={book?.title || 'Book'}
                isGenerating={isGeneratingRecap && generatingSessionId === activeMemoryBridgeSession.id}
                onContinueReading={handleContinueReading}
                onDismiss={handleDismissMemoryBridge}
                onUpdateBoundaries={handleUpdateBoundaries}
                onRegenerateRecap={handleRegenerateRecap}
                totalPages={totalPages}
              />
            </div>
          </div>
        )}

        {loadingUrl ? (
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '16px' }}>
            <ConcentricPortal size={70} />
            <div style={{ fontSize: '0.9rem', color: 'var(--color-primary)', fontFamily: 'var(--font-display)' }}>
              Opening book...
            </div>
          </div>
        ) : (
          <ReaderViewport
            fileUrl={pdfUrl}
            bookId={book?.id || ''}
            currentPage={currentPage}
            zoomScale={zoomScale}
            bookTitle={book?.title || ''}
            annotations={pageAnnotations}
            isAddingNote={isAddingNote}
            onAddNoteAt={handleAddNoteAt}
            onUpdateAnnotation={updateAnnotation}
            onDeleteAnnotation={deleteAnnotation}
            onLoadSuccess={handleDocumentLoadSuccess}
            isQuietReading={isQuietReading}
            isFocusMode={isFocusMode}
          />
        )}

        {/* Sidebar */}
        {activeSidebar && (
          <ReaderSidebar
            mode={activeSidebar}
            totalPages={totalPages}
            currentPage={currentPage}
            bookmarks={bookmarks}
            annotations={bookAnnotations}
            sessions={bookSessions}
            isGeneratingRecap={isGeneratingRecap}
            onSelectPage={handlePageChange}
            onRemoveBookmark={(bmId) => removeBookmark(bmId)}
            onDeleteAnnotation={(annId) => deleteAnnotation(annId)}
            onPinArchiveAsset={handlePinArchiveAsset}
            onUpdateSessionBoundaries={async (sessId, sPage, ePage) => {
              if (book) {
                await updateSessionBoundaries(sessId, sPage, ePage, book.file_path, book.title, book.author);
                showToast({ type: 'success', message: `Boundaries updated to Pages ${sPage}–${ePage}` });
              }
            }}
            onRegenerateSessionRecap={async (sessId) => {
              if (book) {
                const ok = await generateRecapForSession(sessId, book.file_path, book.title, book.author);
                if (ok) showToast({ type: 'success', message: 'Recap regenerated!' });
                else showToast({ type: 'error', message: 'Failed to generate recap. Check Gemini key or network.' });
              }
            }}
            onDeleteSession={async (sessId) => {
              await deleteSession(sessId);
              showToast({ type: 'info', message: 'Reading session record deleted' });
            }}
            onClose={() => setActiveSidebar(null)}
          />
        )}
      </div>
    </div>
  );
};
